import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.scss";
import { Header } from "@/components/organisms/Header/Header";
import { Footer } from "@/components/organisms/Footer/Footer";
import Main from "@/components/organisms/Main/Main";

const montserrat = Montserrat({
    variable: "--font-montserrat",
    subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
    title: "test",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="uk">
            <body
                style={{
                    display: "flex",
                    flexDirection: "column",
                    minHeight: "100dvh",
                }}
                className={montserrat.className}
            >
                <Main />
                <main style={{ flex: 1 }}>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
